Make sure to revalidate instances when mixins are invalidated
webcomponents/shadycss pull request #27
Opened 2016-11-16 20:36 UTC by azakus

Fixes #21

2016-12-01 18:21 UTC, TomK commented
this works for me 👍

2016-12-06 00:58 UTC, sorvell requested changes

2016-12-06 00:58 UTC, sorvell commented on src/ShadyCSS.js
> +    assign(styleInfo.overrideStyleProperties, overrideProps);
remove

2016-12-06 00:58 UTC, sorvell commented on src/ShadyCSS.js
> +        this._applyToDescendants(c.assignedNodes().filter(this._isElementNode));
Let's add an inline comment about why this needs to be here in this exact case.

2016-12-07 19:38 UTC, sorvell requested changes

2016-12-07 19:38 UTC, sorvell commented on src/ShadyCSS.js
> +      } else if (nativeCssVariables && c.localName === 'slot') {
Let's consider not doing this as it's a perf hit (yes, that means the issue still exists).

2016-12-07 19:38 UTC, sorvell commented on src/ShadyCSS.js
> +    if (this._forceRecalc || styleInfo.shouldRecalculate || template._applyShimInvalid) {
let's also bail out of this function early if we detect the element does not use or produce `apply` rules and native properties are in use.

2019-06-07 00:42 UTC, closed without merging